# Generated by Django 5.1.4 on 2024-12-13 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=50, verbose_name='место привычки')),
                ('time', models.DateTimeField(verbose_name='время для привычки')),
                ('action', models.CharField(max_length=200, verbose_name='действие')),
                ('is_nice_habbit', models.BooleanField(default=False, verbose_name='признак приятной привычки')),
                ('periodicity', models.CharField(choices=[('every_day', 'Каждый день'), ('once_2day', 'Раз в 2 дня'), ('once_3day', 'раз в 3 дня')], max_length=30, verbose_name='периодичность')),
                ('reward', models.CharField(help_text='То, что вы получите за выполнение привычки', max_length=100, verbose_name='вознаграждение')),
                ('time_to_complete', models.DurationField(help_text='в секундах(до 120 сек)', verbose_name='длительность выполнения привычки')),
                ('publish_to_all', models.BooleanField(choices=[(False, 'Видна мне'), (True, 'Видна всем')], help_text='привычка будет видна всем или только вам', verbose_name='признак публичности')),
                ('chained_habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nice_habbits', to='tracker.habit', verbose_name='приятная привычка')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
            },
        ),
    ]
