# Generated by Django 5.1.4 on 2024-12-17 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_habit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='chained_habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nice_habbits', to='tracker.habit', verbose_name='приятная привычка'),
        ),
    ]
