# Generated by Django 5.1.4 on 2024-12-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_habit_chained_habit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='is_nice_habbit',
            new_name='is_nice_habit',
        ),
        migrations.AlterField(
            model_name='habit',
            name='periodicity',
            field=models.CharField(choices=[('every_day', 'Каждый день'), ('once_2day', 'Раз в 2 дня'), ('once_3day', 'раз в 3 дня')], default='every_day', max_length=30, verbose_name='периодичность'),
        ),
    ]
