# Generated by Django 5.1.4 on 2024-12-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_rename_is_nice_habbit_habit_is_nice_habit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='reward',
            field=models.CharField(blank=True, help_text='То, что вы получите за выполнение привычки', max_length=100, null=True, verbose_name='вознаграждение'),
        ),
    ]
