# Generated by Django 5.1.4 on 2024-12-18 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_alter_habit_place_alter_habit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='periodicity',
            field=models.CharField(choices=[('every_day', 'Каждый день'), ('once_2day', 'Раз в 2 дня'), ('once_3day', 'раз в 3 дня'), ('once_week', 'раз в неделю')], default='every_day', max_length=30, verbose_name='периодичность'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='time_to_complete',
            field=models.DurationField(blank=True, help_text='в секундах(до 120 сек)', null=True, verbose_name='длительность выполнения привычки'),
        ),
    ]
