# Generated by Django 5.1.4 on 2024-12-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_alter_habit_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='periodicity',
            field=models.CharField(choices=[(1440, 'Каждый день'), (2880, 'Раз в 2 дня'), (4320, 'раз в 3 дня'), (10080, 'раз в неделю')], default='every_day', max_length=30, verbose_name='периодичность'),
        ),
    ]
