# Generated by Django 5.1.4 on 2024-12-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_alter_habit_periodicity'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='last_notification',
            field=models.DateTimeField(default=None, verbose_name='последнее уведомление'),
        ),
    ]
